Transform: 'AWS::Serverless-2016-10-31'
Resources:
    GetSAMPartyCount:
        Type: AWS::Serverless::Function
        Properties:
            Handler: lambda_function.lambda_handler
            Runtime: python3.6
            CodeUri: ./
